/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  62N_PBGlider                                   */
/*      FILE         :  62N_PBGlider.cpp                               */
/*      DESCRIPTION  :  Main Program                                   */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  RX62N                                          */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/                                                                         
                                                                           
                                                                           
                                                                           
                                                                          
/***********************************************************************/
/*                                                                     */
/*  FILE        :Main.c or Main.cpp                                    */
/*  DATE        :Tue, Oct 31, 2006                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :                                                      */
/*                                                                     */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

#include "GeneralConfig.hpp"
#include "Peripherals/StdSci.hpp"
#include "Peripherals/CrReceivedHandler.hpp"
#include "Peripherals/Hals/HalSci0.hpp"
#include "Util.hpp"
#include "Peripherals/OrientationFilter.hpp"
#include "Peripherals/Storage.hpp"
#include "Peripherals/Hals/HalFlash.hpp"
#include "Peripherals/RangeFinder.hpp"
#include "Peripherals/Hals/HalRangeFinderMtu.hpp"


void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void initSystem(){
	SYSTEM.SCKCR.LONG = 0x20100;	// ICLK=96MHz,BCLK=24MHz,PCLK=48MHz
}

void initPeriperals(){
	if(HalSci0::getInstance() == NULL){
		Util::myException("malloc error at initPeripherals\n\r");
	}
	if(HalSci5::getInstance() == NULL){
		Util::myException("malloc error at initPeripherals\n\r");
	}
	if(HalRangeFinderMtu::getInstance() == NULL){
		Util::myException("malloc error at initPeripherals\n\r");
	}

	stdout = new StdSci(HalSci0::getInstance());

	if(stdout==NULL){
		Util::myException("malloc error at initPeripherals\n\r");
	}
	HalSci0::getInstance()->setCrReceivedHandler(new CrReceivedHandler(HalSci0::getInstance()));
	Storage::init();

	gps = new GpsCrReceivedHandler(HalSci5::getInstance());
	HalSci5::getInstance()->setCrReceivedHandler(gps);



	mpu9150 = new Mpu9150();
	if(mpu9150==NULL){
		Util::myException("malloc error at initPeripherals\n\r");
	}
	inu = new Inu();
	if(inu==NULL){
		Util::myException("malloc error at initPeripherals\n\r");
	}
	mpu9150->readGyroBias();
	mpu9150->readCompassBias();

	rangeFinder = new RangeFinder(HalRangeFinderMtu::getInstance());
	if(rangeFinder==NULL){
		Util::myException("malloc error at initPeripherals\n\r");
	}


	mpu9150->start();
	rangeFinder->start();

	HalServoMtus::getInstance()->start();
	HalSci0::getInstance()->start();
	HalSci5::getInstance()->start();

	controlLoop = new ControlLoop();
}

void main(void)
{
	initSystem();
	initPeriperals();

	PORTD.DDR.BIT.B7 = 1;

	controlLoop->controlLoop();
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
