/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  62N_PBGlider                                   */
/*      FILE         :  sbrk.h                                         */
/*      DESCRIPTION  :  Header file of sbrk file                       */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  RX62N                                          */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x1000
