/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  62N_PBGlider                                   */
/*      FILE         :  stacksct.h                                     */
/*      DESCRIPTION  :  Setting of Stack area                          */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  RX62N                                          */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/
#pragma stacksize su=0x200
#pragma stacksize si=0x600
